name       : xprintidle
version    : 0.2.2
release    : 1
source     :
    - https://github.com/g0hl1n/xprintidle/archive/0.2.2.tar.gz : 8484ac3c748214ae8330f84974bf92aee76033a4072ea86b02cd0f831ac0b6a6
license    : GPL-2.0-or-later
component  : xorg.library
summary    : Print X idle time
description: |
    xprintidle is a utility that queries the X server for the user's idletime and prints it to stdout (in milliseconds).
builddeps  :
    - pkgconfig(xscrnsaver)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
