name       : xprintidle
version    : 0.2.4
release    : 2
source     :
    - https://github.com/g0hl1n/xprintidle/archive/refs/tags/0.2.4.tar.gz : fe4e14743a449d67917babc7b29082e12e1a4bfff7efe4b88e3a34a5fc791d01
homepage    : https://github.com/g0hl1n/xprintidle
license    : GPL-2.0-only
component  : xorg.library
summary    : Print X idle time
description: |
    xprintidle is a utility that queries the X server for the user's idle time and prints it to stdout (in milliseconds).
builddeps  :
    - pkgconfig(xscrnsaver)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
