name       : xprintidle
version    : 0.2.5
release    : 3
source     :
    - https://github.com/g0hl1n/xprintidle/archive/refs/tags/0.2.5.tar.gz : 1c0349e555fe310284c82e8ca3c43318e09cea0874552aadadc33a14d5946232
homepage   : https://github.com/g0hl1n/xprintidle
license    : GPL-2.0-only
component  : xorg.library
summary    : Print X idle time
description: |
    xprintidle is a utility that queries the X server for the user's idle time and prints it to stdout (in milliseconds).
builddeps  :
    - pkgconfig(xscrnsaver)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
